### ISSUE TITLE
Color-coding of nodes by file type in dot/graphviz output

### ISSUE THREAD

**Issue by davidlav** [sverweij/dependency-cruiser#59]
### Expected Behavior
File nodes produced in dot "mode" would be color-coded based on file type.  Maybe yellow for JavaScript, blue for TypeScript, etc.  (This might be worth a separate issue request all together, but some sort of visual indication/highlighting of orphaned nodes---files that are neither reference other files nor are referenced by other files---could be very helpful too.)

### Current Behavior
Currently all file nodes are the same pale yellow color regardless of file type.

### Context
I'm using the graphviz dependency tree to help migrate a JavaScript project over to a TypeScript one, and color-coded nodes by file type would be extremely helpful for knowing what's already been converted, and what's left to do.

Fantastic project though!  Been looking for something like this for a long time, great work!!

**Comment by sverweij** [comment]
@davidlav good suggestion, thanks! It shouldn't be too hard to implement. The only challenge is to make it easy to use (good results with as little configuration as possible - but enough flexibility to customize). I'll mull it over today and see if I an whip something up after.

B.t.w. I did a quick spike with a file pattern (fillcolor everything that includes _template_ light blue): 

<img width="601" alt="screen shot 2018-08-15 at 07 10 13" src="https://user-images.githubusercontent.com/4822597/44132495-649b2e56-a05a-11e8-9647-5060531dbcc3.png">

**Comment by sverweij** [comment]
@davidlav I've published dependency-cruiser version 4.5.0-beta-0 on npm (with the beta tag), which (with some hardcoded, ugly prototype code) applies these background fill colors in the dot reporter:

- .ts => light blue
- .json => orange-ish
- .orphan => sickly green
- .coffee => brownish
- (all other modules keep the default yellow-is color)

This what you're looking for? If so I'll make the implementation a little cleaner and publish it to npm main later (maybe this weekend, maybe somewhat later). 

(In case you're not familiar with npm tags - it works quite transparently -  `npm i -D dependency-cruiser@4.5.0-beta-0` will install this specific version;  `npm i -D dependency-cruiser@beta` will add the latest beta)

**Comment by davidlav** [comment]
That's great!  Just tried it out and while the TypeScript highlighting works great, it didn't catch the one orphaned file I've got.  Also, could you set it to color .tsx (TypeScript React) files the same color as .ts?  Thanks

**Comment by sverweij** [comment]
@davidlav thanks for checking it out and the feedback.

- on the orphaned thing - I'll check it; it's entirely possible I made a typo in the prototype - there's only so much I could do before rushing off to work :-)
- .tsx c.s. - of course. I'll try & complete the (default) list with all supported extensions (.d.ts, .jsx, .vue, .coffee, cjsx, csx, .litcoffee, ...).

**Comment by davidlav** [comment]
Thanks so much, your turn-around time is impressive!  For some reason it's still not picking up my orphaned file ("util/async.js").  Below is part of the image the beta-1 release produced.

![image](https://user-images.githubusercontent.com/18689323/44183653-7cf77000-a0d1-11e8-998d-45f4ad2e25fb.png)

**Comment by sverweij** [comment]
@davidlav thanks for the compliment, and thank _you_ for your quick feedback.

@ the orphaned file: I've rechecked (both IRL & with unit test) but can't reproduce it. Just checking some assumptions:
- Does your setup have a `.dependency-cruiser.json`? (if not, the easiest way to create one is `depcruise --init` - the resulting file contains a.o. a orphan detection rule)
- To create this diagram, do you run dependency-cruiser with validations (`--validate --output-type dot` (/`-v -T dot`))?
- If you do use `--validate` and a `.dependency-cruiser.json` - does that file contain a rule to detect orphans? (if not, add below object to the `forbidden` section)
- If you run dependency cruiser with `--validate --output-type err` (/`-v -T err`), does the orphan show up there?

If all these questions have _yes_ as an answer you've hit a bug - in which case I probably need some extra information in order to solve it...

```json
    {
        "name": "no-orphans",
        "severity": "info",
        "comment": "Inform in case there's orphans hiding in the code base",
        "from": { "orphan": true, "pathNot": "\\.d\\.ts$" },
        "to": {}
    }
```

**Comment by davidlav** [comment]
Thank you for walking me through that!  I had neither the json file nor the --validate flag.  Works like a charm now!

**Comment by sverweij** [comment]
Version `4.5.0-beta-2` is on npm. Changes w.r.t. beta-1:
- the color scheme slightly changed (for you: .ts and .tsx are still both pale blue, but slightly differ between each other) - see the PR for an overview of the most regular ones.
- the `dot` reporter is back to its old behaviour. The more rich coloring is in the new `rcdot` reporter - the description of the PR contains a sample command line.

Feedback still welcome!

**Comment by sverweij** [comment]
Regular release `4.5.0` with this (and an other) feature is on npm now - details in the [release notes](https://github.com/sverweij/dependency-cruiser/releases/tag/v4.5.0). Thanks again for raising this feature request!

**Comment by davidlav** [comment]
Thank you!
